import Bun from "bun";
import fs from "node:fs";
import { flattenLibrary } from "../utils/library";
import { tokenLibrary } from "../tokens";

const OUT_PATH = "dist/styles/tokens.css";

const generateCss = async () => {
  const flatLibrary = flattenLibrary(tokenLibrary);
  const css = Object.entries(flatLibrary)
    .map(([key, value]) => {
      return `\t--${key.replace(/\./g, "-")}: ${value.$value};`;
    })
    .join("\n");

  const cssFile =
    "/* This file is generated by the design system. Do not edit it manually. */\n\n" +
    `:root {\n${css}\n}
    `;

  if (fs.existsSync(OUT_PATH)) fs.unlinkSync(OUT_PATH);
  await Bun.write(OUT_PATH, cssFile);
};

generateCss();
